In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv('loan_data.csv');

In [4]:
dataset.head()

credit.policy             purpose  int.rate  installment  log.annual.inc  \
0              1  debt_consolidation    0.1189       829.10       11.350407   
1              1         credit_card    0.1071       228.22       11.082143   
2              1  debt_consolidation    0.1357       366.86       10.373491   
3              1  debt_consolidation    0.1008       162.34       11.350407   
4              1         credit_card    0.1426       102.92       11.299732   

     dti  fico  days.with.cr.line  revol.bal  revol.util  inq.last.6mths  \
0  19.48   737        5639.958333      28854        52.1               0   
1  14.29   707        2760.000000      33623        76.7               0   
2  11.63   682        4710.000000       3511        25.6               1   
3   8.10   712        2699.958333      33667        73.2               1   
4  14.97   667        4066.000000       4740        39.5               0   

   delinq.2yrs  pub.rec  not.fully.paid  
0            0        0               0  
1            0        0               0  
2            0        0               0  
3            0        0               0  
4            1        0               0

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 14 columns):
credit.policy        9578 non-null int64
purpose              9578 non-null object
int.rate             9578 non-null float64
installment          9578 non-null float64
log.annual.inc       9578 non-null float64
dti                  9578 non-null float64
fico                 9578 non-null int64
days.with.cr.line    9578 non-null float64
revol.bal            9578 non-null int64
revol.util           9578 non-null float64
inq.last.6mths       9578 non-null int64
delinq.2yrs          9578 non-null int64
pub.rec              9578 non-null int64
not.fully.paid       9578 non-null int64
dtypes: float64(6), int64(7), object(1)
memory usage: 1.0+ MB


In [6]:
cat_feats = ['purpose']

In [9]:
final_data = pd.get_dummies(dataset,columns=cat_feats,drop_first=True)

In [10]:
final_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9578 entries, 0 to 9577
Data columns (total 19 columns):
credit.policy                 9578 non-null int64
int.rate                      9578 non-null float64
installment                   9578 non-null float64
log.annual.inc                9578 non-null float64
dti                           9578 non-null float64
fico                          9578 non-null int64
days.with.cr.line             9578 non-null float64
revol.bal                     9578 non-null int64
revol.util                    9578 non-null float64
inq.last.6mths                9578 non-null int64
delinq.2yrs                   9578 non-null int64
pub.rec                       9578 non-null int64
not.fully.paid                9578 non-null int64
purpose_credit_card           9578 non-null uint8
purpose_debt_consolidation    9578 non-null uint8
purpose_educational           9578 non-null uint8
purpose_home_improvement      9578 non-null uint8
purpose_major_purchase        9

In [12]:
final_data.head()

credit.policy  int.rate  installment  log.annual.inc    dti  fico  \
0              1    0.1189       829.10       11.350407  19.48   737   
1              1    0.1071       228.22       11.082143  14.29   707   
2              1    0.1357       366.86       10.373491  11.63   682   
3              1    0.1008       162.34       11.350407   8.10   712   
4              1    0.1426       102.92       11.299732  14.97   667   

   days.with.cr.line  revol.bal  revol.util  inq.last.6mths  delinq.2yrs  \
0        5639.958333      28854        52.1               0            0   
1        2760.000000      33623        76.7               0            0   
2        4710.000000       3511        25.6               1            0   
3        2699.958333      33667        73.2               1            0   
4        4066.000000       4740        39.5               0            1   

   pub.rec  not.fully.paid  purpose_credit_card  purpose_debt_consolidation  \
0        0               0                    0                           1   
1        0               0                    1                           0   
2        0               0                    0                           1   
3        0               0                    0                           1   
4        0               0                    1                           0   

   purpose_educational  purpose_home_improvement  purpose_major_purchase  \
0                    0                         0                       0   
1                    0                         0                       0   
2                    0                         0                       0   
3                    0                         0                       0   
4                    0                         0                       0   

   purpose_small_business  
0                       0  
1                       0  
2                       0  
3                       0  
4                       0

In [13]:
from sklearn.cross_validation import train_test_split

In [14]:
X = final_data.drop('not.fully.paid',axis = 1)
y = final_data['not.fully.paid']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [15]:
from sklearn.tree import DecisionTreeClassifier

In [16]:
dtree = DecisionTreeClassifier()
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [17]:
y_pred = dtree.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix,classification_report
print confusion_matrix(y_test,y_pred)
print '\n'
print classification_report(y_test,y_pred)

[[2168  498]
 [ 378  117]]


             precision    recall  f1-score   support

          0       0.85      0.81      0.83      2666
          1       0.19      0.24      0.21       495

avg / total       0.75      0.72      0.73      3161



In [19]:
from sklearn.ensemble import RandomForestClassifier


In [20]:
rfc = RandomForestClassifier(n_estimators=300)

In [21]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [22]:
y_pred = rfc.predict(X_test)

In [23]:
print confusion_matrix(y_test,y_pred)
print '\n'
print classification_report(y_test,y_pred)

[[2655   11]
 [ 486    9]]


             precision    recall  f1-score   support

          0       0.85      1.00      0.91      2666
          1       0.45      0.02      0.03       495

avg / total       0.78      0.84      0.78      3161



In [24]:
from sklearn.grid_search import GridSearchCV

/Users/rishav/anaconda2/lib/python2.7/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [26]:
para_grid = {'n_estimators':[10,50,100,150,200,250,300],'criterion':['gini','entropy']}

In [27]:
grid = GridSearchCV(RandomForestClassifier(),para_grid,verbose=3)

In [28]:
grid.fit(X_train,y_train)

Fitting 3 folds for each of 14 candidates, totalling 42 fits
[CV] n_estimators=10, criterion=gini .................................
[CV] ........ n_estimators=10, criterion=gini, score=0.832165 -   0.1s
[CV] n_estimators=10, criterion=gini .................................
[CV] ........ n_estimators=10, criterion=gini, score=0.835437 -   0.1s
[CV] n_estimators=10, criterion=gini .................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.2s remaining:    0.0s


[CV] ........ n_estimators=10, criterion=gini, score=0.827489 -   0.1s
[CV] n_estimators=50, criterion=gini .................................
[CV] ........ n_estimators=50, criterion=gini, score=0.836372 -   0.4s
[CV] n_estimators=50, criterion=gini .................................
[CV] ........ n_estimators=50, criterion=gini, score=0.837307 -   0.4s
[CV] n_estimators=50, criterion=gini .................................
[CV] ........ n_estimators=50, criterion=gini, score=0.829360 -   0.5s
[CV] n_estimators=100, criterion=gini ................................
[CV] ....... n_estimators=100, criterion=gini, score=0.836840 -   0.8s
[CV] n_estimators=100, criterion=gini ................................
[CV] ....... n_estimators=100, criterion=gini, score=0.839177 -   0.9s
[CV] n_estimators=100, criterion=gini ................................
[CV] ....... n_estimators=100, criterion=gini, score=0.831697 -   0.8s
[CV] n_estimators=150, criterion=gini ................................
[CV] .

[Parallel(n_jobs=1)]: Done  42 out of  42 | elapsed:   58.5s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'n_estimators': [10, 50, 100, 150, 200, 250, 300], 'criterion': ['gini', 'entropy']},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=3)

In [29]:
grid.best_params_

{'criterion': 'entropy', 'n_estimators': 100}

In [30]:
rfc = RandomForestClassifier(n_estimators=100,criterion='entropy')

In [31]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [32]:
y_pred = rfc.predict(X_test)

In [33]:
print confusion_matrix(y_test,y_pred)
print '\n'
print classification_report(y_test,y_pred)

[[2654   12]
 [ 485   10]]


             precision    recall  f1-score   support

          0       0.85      1.00      0.91      2666
          1       0.45      0.02      0.04       495

avg / total       0.78      0.84      0.78      3161

