In [ ]:
import numpy as np

In [3]:
a = np.array([0,1,2,3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
#Python List
L = range(1000)
%timeit [i**2 for i in L]

258 µs ± 4.53 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
a = np.arange(1000)
%timeit a**2

1.08 µs ± 32.9 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [8]:
a = np.array([0,1,2,3])
print(a)
print("Dimensiona of Array :",a.ndim) # return dimension
print("Shape of Vector :",a.shape)
print("Length of array :",len(a))

[0 1 2 3]
Dimensiona of Array : 1
Shape of Vector : (4,)
Length of array : 4


In [9]:
b = np.array([[0,1,2],[3,4,5]])
print(b)
print("Dimensiona of Array :",b.ndim) # return dimension
print("Shape of Vector :",b.shape)
print("Length of array :",len(b))

[[0 1 2]
 [3 4 5]]
Dimensiona of Array : 2
Shape of Vector : (2, 3)
Length of array : 2


In [10]:
c = np.array([[0,1],[2,3], [[4,5],[6,7]]])
print(c)
print("Dimensiona of Array :",c.ndim) # return dimension
print("Shape of Vector :",c.shape)
print("Length of array :",len(c))

[[0 1]
 [2 3]
 [list([4, 5]) list([6, 7])]]
Dimensiona of Array : 2
Shape of Vector : (3, 2)
Length of array : 3


## function for creating arrays

In [11]:
a = np.arange(10)
print(a)
b = np.arange(1,10,2)
print(b)
c = np.linspace(0,1,6) #start end stepwise
print(c)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[0.  0.2 0.4 0.6 0.8 1. ]


In [12]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [17]:
d = np.diag([1,2,3,4])

In [18]:
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [19]:
np.diag(d)

array([1, 2, 3, 4])

In [20]:
a = np.random.rand(4)
a

array([0.46290408, 0.81040164, 0.17798   , 0.65820461])

In [21]:
a = np.random.randn(4)
a

array([-0.15624615, -1.15705731,  0.12937205,  0.8109131 ])

## Basic DataTypes

In [22]:
a = np.arange(10)
a.dtype

dtype('int64')

In [23]:
a = np.arange(10,dtype="float64")
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
a = np.zeros((3,3))
print(a)
print("\n")
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


float64


In [27]:
d = np.array([1+2j,2+4j])
print(d.dtype)

complex128


In [30]:
b = np.array([True,False,True,False])
print(b.dtype)

bool


In [31]:
s = np.array(['Ram','Robert','hack'])
print(s.dtype)

<U6


In [32]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [35]:
np.shares_memory(a,b)

True

In [36]:
b[0]= 10
b

array([10,  2,  4,  6,  8])

In [37]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [38]:
a = np.arange(10)
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [39]:
np.shares_memory(a,c)

False

In [40]:
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Fancy Indexing

In [49]:
a = np.random.randint(0,20,15)
a

array([10,  6,  2, 19, 16,  5, 11, 11, 14, 13, 13, 10,  6,  8, 17])

In [50]:
mask = (a % 2 == 0)

In [51]:
extract_from_a = a[mask]
extract_from_a

array([10,  6,  2, 16, 14, 10,  6,  8])

In [52]:
a[mask] = 8
a

array([ 8,  8,  8, 19,  8,  5, 11, 11,  8, 13, 13,  8,  8,  8, 17])

### indexing with an array of integer


In [53]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
a[[2,3,4,2,3]] #index

array([20, 30, 40, 20, 30])

In [55]:
a[[9,7]] = -800
a

array([   0,   10,   20,   30,   40,   50,   60, -800,   80, -800])

## Elementwise Operations

### 1. Basic Operations with scalars

In [2]:
import numpy as np
a = np.array([1,2,3,4]) #Create an array
 
a + 1

array([2, 3, 4, 5])

In [3]:
a ** 2

array([ 1,  4,  9, 16])

### All arithmetic operates elementwise

In [4]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [5]:
a * b

array([2., 4., 6., 8.])

In [9]:
c = np.diag([1,2,3,4])

print(c*c)
print("\n")
print("***********")
print("\n")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


***********


[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [10]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])

a == b

array([False,  True, False,  True])

In [11]:
a > b

array([False, False,  True, False])

In [13]:
# Array-wise comparision
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])

np.array_equal(a,b)

False

In [14]:
np.array_equal(a,c)

True

### Logical Operations

In [15]:
a = np.array([1,1,0,0],dtype=bool)

In [16]:
b = np.array([1,0,1,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False])

In [17]:
np.logical_and(a,b)

array([ True, False, False, False])

### Transcendental functions:

In [18]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [19]:
np.log(a)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [20]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### Shape Mismatch

In [21]:
a = np.arange(4)
a + np.array([1,2])

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

### Basic REducations

#### Computing sums

In [1]:
import numpy as np
x = np.array([1,2,3,4])
np.sum(x)

10

In [2]:
#Sum by rows and by colums
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [4]:
x.sum(axis=0)

array([3, 3])

In [5]:
x.sum(axis=1)

array([2, 4])

### Other reducations

In [6]:
x = np.array([1,3,2])
x.min()

1

In [7]:
x.max()

3

In [8]:
x.argmin() #index of minimum element

0

In [9]:
x.argmax() #index of maximum element

1

### Logical Operations

In [10]:
np.all([True,True,False])

False

In [11]:
np.any([True,False,False])

True

In [12]:
#Note: can be used for array comparisions
a = np.zeros((50,50))
np.any(a != 0)

False

In [13]:
np.all(a == a)

True

### Statistics

In [1]:
import numpy as np
x = np.array([1,2,3,1])
y = np.array([[1,2,3],[5,6,1]])
x.mean()

1.75

In [2]:
np.median(x)

1.5

In [3]:
np.median(y,axis=-1) #Last axis

array([2., 5.])

In [4]:
x.std()

0.82915619758885

## Broadcasting

Basic operations on numpy arrays(addition,etc.) are elementwise

This work on arrays of the same size. Nevertheless.it's also possible to do operations on array of different size if Numpy can transform these arrays so that they all have the same size: this conversion is called broadcasting


In [5]:
np.arange(0,40,10)

array([ 0, 10, 20, 30])

In [6]:
a = np.tile(np.arange(0,40,10),(3,1))
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]


In [7]:
a = a.T
print(a)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [8]:
b = np.array([0,1,2])
print(b)

[0 1 2]


In [9]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [10]:
a = np.arange(0,40,10)
a.shape

(4,)

In [11]:
a = a[:,np.newaxis] ## Adds new Axis -> 2D arrays
a.shape

(4, 1)

In [12]:
a

array([[ 0],
       [10],
       [20],
       [30]])

## Array shape Manipulation

##### Flattening

In [2]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a.ravel() #REturn. a contigous flateed array. 1D Array

array([1, 2, 3, 4, 5, 6])

In [3]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

### Reshaping

##### The inverse operation to flattening:

In [7]:
print(a.shape)
print("****")
print(a)

(2, 3)
****
[[1 2 3]
 [4 5 6]]


In [8]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [9]:
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
b[0,0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

### Note and Beware: reshape may also return a copy!:

In [11]:
a = np.zeros((3,2))
b = a.T.reshape(3*2)
b[0] = 50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## Adding a Dimension

In [12]:
z = np.array([1,2,3])
z

array([1, 2, 3])

In [13]:
z[:,np.newaxis]

array([[1],
       [2],
       [3]])

### Dimension shuffling

In [14]:
a = np.arange(4*3*2).reshape(4,3,2)
a.shape

(4, 3, 2)

In [15]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [16]:
a[0,2,1]

5

### Resizing

In [19]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

### However,it must not be referred to somewhere else:

In [20]:
b = a
a.resize((4,)) # a.shape is 8 

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

### Sorting Data

## Sorting along an axis:


In [21]:
a = np.array([[5,4,6],[2,3,3]])
b = np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 3, 3]])

In [22]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 3, 3]])

In [28]:
# Sorting with fancy indexing
a = np.array([4,3,1,2])
j = np.argsort(a) #Return index
j

array([2, 3, 1, 0])

In [29]:
a[j]

array([1, 2, 3, 4])