In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [3]:
my_mat = [[1,2,3],[2,3,4],[5,6,7],[8,9,7]]

In [2]:
my_mat

[[1, 2, 3], [2, 3, 4], [5, 6, 7], [8, 9, 7]]

In [4]:
import numpy as np
np.array(my_mat)

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7],
       [8, 9, 7]])

In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [10]:
np.linspace(0,5,8)

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429, 5.        ])

In [17]:
np.eye(4) #identical array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.03793627, 0.58797418, 0.6688806 , 0.40351317, 0.10188356])

In [19]:
np.random.rand(5,5)

array([[0.37046369, 0.79047994, 0.12220062, 0.49826641, 0.11123196],
       [0.12337222, 0.93833357, 0.81032206, 0.31481404, 0.71841076],
       [0.69722179, 0.45645203, 0.37964094, 0.08425626, 0.89839113],
       [0.88645328, 0.08116346, 0.23858174, 0.87945302, 0.5988438 ],
       [0.237698  , 0.1402563 , 0.31054574, 0.54004951, 0.04882656]])

In [12]:
np.random.randn(3)

array([ 1.82115406,  0.24199325, -2.21310253])

In [21]:
np.random.randn(4,4)

array([[ 1.29055345, -0.77150181,  0.07892588, -0.60509261],
       [-0.62888262, -0.33912301, -0.56265471,  0.86028637],
       [ 1.04475842, -0.10762163,  0.10991138, -0.07363969],
       [-0.55721418, -0.28432546, -1.64308989,  0.72217135]])

In [22]:
np.random.randint(1,100)

93

In [23]:
np.random.randint(1,100,10)

array([66, 26, 48, 27, 92, 95, 99, 30, 78, 19])

In [24]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)

In [27]:
ranarr

array([31, 31,  0, 45,  9, 23, 13, 39, 22, 28])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
arr.reshape(5,10) #its create array 12:30 video m dekho..No.Of row === no of column

ValueError: cannot reshape array of size 25 into shape (5,10)

In [30]:
ranarr.max()

45

In [31]:
ranarr.min()

0

In [32]:
ranarr.min()

0

In [33]:
ranarr

array([31, 31,  0, 45,  9, 23, 13, 39, 22, 28])

In [34]:
ranarr.argmax() #Postion of maximun number

3

In [35]:
ranarr.argmin()

2

In [36]:
arr.shape

(25,)

In [38]:
arr = arr.reshape(5,5)

In [39]:
arr.shape

(5, 5)

In [40]:
arr.dtype

dtype('int32')

In [41]:
from numpy.random import randint

In [42]:
randint(2,10)

3