In [25]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [26]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:,[2,3]].values
y = dataset.iloc[:,4].values

In [27]:
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [29]:
from sklearn.svm import SVC
classifier = SVC(kernel='linear',random_state=0)
classifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=0, shrinking=True,
  tol=0.001, verbose=False)

In [30]:
y_pred = classifier.predict(X_test)

In [31]:
from sklearn.metrics import confusion_matrix,classification_report
print classification_report(y_test,y_pred)
print '\n'
print confusion_matrix(y_test,y_pred)

             precision    recall  f1-score   support

          0       0.90      0.93      0.91        68
          1       0.83      0.78      0.81        32

avg / total       0.88      0.88      0.88       100



[[63  5]
 [ 7 25]]


In [32]:
from sklearn.grid_search import GridSearchCV

/Users/rishav/anaconda2/lib/python2.7/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)


In [41]:
para_grid = {'C':[0.1,1,10,100,1000],'gamma':[1,0.1,0.01,0.001,0.0001],'kernel':['linear', 'poly', 'rbf', 'sigmoid']}

In [42]:
grid = GridSearchCV(SVC(),para_grid,verbose=3)

In [43]:
grid.fit(X_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] kernel=linear, C=0.1, gamma=1 ...................................
[CV] .......... kernel=linear, C=0.1, gamma=1, score=0.780000 -   0.0s
[CV] kernel=linear, C=0.1, gamma=1 ...................................
[CV] .......... kernel=linear, C=0.1, gamma=1, score=0.770000 -   0.0s
[CV] kernel=linear, C=0.1, gamma=1 ...................................
[CV] .......... kernel=linear, C=0.1, gamma=1, score=0.900000 -   0.0s
[CV] kernel=poly, C=0.1, gamma=1 .....................................
[CV] ............ kernel=poly, C=0.1, gamma=1, score=0.820000 -   0.0s
[CV] kernel=poly, C=0.1, gamma=1 .....................................
[CV] ............ kernel=poly, C=0.1, gamma=1, score=0.740000 -   0.0s
[CV] kernel=poly, C=0.1, gamma=1 .....................................
[CV] ............ kernel=poly, C=0.1, gamma=1, score=0.860000 -   0.0s
[CV] kernel=rbf, C=0.1, gamma=1 ......................................
[CV] .........

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s



[CV] ........ kernel=rbf, C=0.1, gamma=0.0001, score=0.630000 -   0.0s
[CV] kernel=rbf, C=0.1, gamma=0.0001 .................................
[CV] ........ kernel=rbf, C=0.1, gamma=0.0001, score=0.630000 -   0.0s
[CV] kernel=sigmoid, C=0.1, gamma=0.0001 .............................
[CV] .... kernel=sigmoid, C=0.1, gamma=0.0001, score=0.630000 -   0.0s
[CV] kernel=sigmoid, C=0.1, gamma=0.0001 .............................
[CV] .... kernel=sigmoid, C=0.1, gamma=0.0001, score=0.630000 -   0.0s
[CV] kernel=sigmoid, C=0.1, gamma=0.0001 .............................
[CV] .... kernel=sigmoid, C=0.1, gamma=0.0001, score=0.630000 -   0.0s
[CV] kernel=linear, C=1, gamma=1 .....................................
[CV] ............ kernel=linear, C=1, gamma=1, score=0.790000 -   0.0s
[CV] kernel=linear, C=1, gamma=1 .....................................
[CV] ............ kernel=linear, C=1, gamma=1, score=0.760000 -   0.0s
[CV] kernel=linear, C=1, gamma=1 .....................................
[CV] 

[CV] ......... kernel=poly, C=10, gamma=0.001, score=0.630000 -   0.0s
[CV] kernel=rbf, C=10, gamma=0.001 ...................................
[CV] .......... kernel=rbf, C=10, gamma=0.001, score=0.760000 -   0.0s
[CV] kernel=rbf, C=10, gamma=0.001 ...................................
[CV] .......... kernel=rbf, C=10, gamma=0.001, score=0.730000 -   0.0s
[CV] kernel=rbf, C=10, gamma=0.001 ...................................
[CV] .......... kernel=rbf, C=10, gamma=0.001, score=0.880000 -   0.0s
[CV] kernel=sigmoid, C=10, gamma=0.001 ...............................
[CV] ...... kernel=sigmoid, C=10, gamma=0.001, score=0.720000 -   0.0s
[CV] kernel=sigmoid, C=10, gamma=0.001 ...............................
[CV] ...... kernel=sigmoid, C=10, gamma=0.001, score=0.710000 -   0.0s
[CV] kernel=sigmoid, C=10, gamma=0.001 ...............................
[CV] ...... kernel=sigmoid, C=10, gamma=0.001, score=0.740000 -   0.0s
[CV] kernel=linear, C=10, gamma=0.0001 ...............................
[CV] .

[CV] ......... kernel=rbf, C=100, gamma=0.001, score=0.760000 -   0.0s
[CV] kernel=rbf, C=100, gamma=0.001 ..................................
[CV] ......... kernel=rbf, C=100, gamma=0.001, score=0.920000 -   0.0s
[CV] kernel=sigmoid, C=100, gamma=0.001 ..............................
[CV] ..... kernel=sigmoid, C=100, gamma=0.001, score=0.780000 -   0.0s
[CV] kernel=sigmoid, C=100, gamma=0.001 ..............................
[CV] ..... kernel=sigmoid, C=100, gamma=0.001, score=0.770000 -   0.0s
[CV] kernel=sigmoid, C=100, gamma=0.001 ..............................
[CV] ..... kernel=sigmoid, C=100, gamma=0.001, score=0.900000 -   0.0s
[CV] kernel=linear, C=100, gamma=0.0001 ..............................
[CV] ..... kernel=linear, C=100, gamma=0.0001, score=0.790000 -   0.0s
[CV] kernel=linear, C=100, gamma=0.0001 ..............................
[CV] ..... kernel=linear, C=100, gamma=0.0001, score=0.760000 -   0.0s
[CV] kernel=linear, C=100, gamma=0.0001 ..............................
[CV] .

[CV] ...... kernel=poly, C=1000, gamma=0.0001, score=0.630000 -   0.0s
[CV] kernel=poly, C=1000, gamma=0.0001 ...............................
[CV] ...... kernel=poly, C=1000, gamma=0.0001, score=0.630000 -   0.0s
[CV] kernel=poly, C=1000, gamma=0.0001 ...............................
[CV] ...... kernel=poly, C=1000, gamma=0.0001, score=0.630000 -   0.0s
[CV] kernel=rbf, C=1000, gamma=0.0001 ................................
[CV] ....... kernel=rbf, C=1000, gamma=0.0001, score=0.790000 -   0.0s
[CV] kernel=rbf, C=1000, gamma=0.0001 ................................
[CV] ....... kernel=rbf, C=1000, gamma=0.0001, score=0.760000 -   0.0s
[CV] kernel=rbf, C=1000, gamma=0.0001 ................................
[CV] ....... kernel=rbf, C=1000, gamma=0.0001, score=0.930000 -   0.0s
[CV] kernel=sigmoid, C=1000, gamma=0.0001 ............................
[CV] ... kernel=sigmoid, C=1000, gamma=0.0001, score=0.780000 -   0.0s
[CV] kernel=sigmoid, C=1000, gamma=0.0001 ............................
[CV] .

[Parallel(n_jobs=1)]: Done 300 out of 300 | elapsed:    3.3s finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'kernel': ['linear', 'poly', 'rbf', 'sigmoid'], 'C': [0.1, 1, 10, 100, 1000], 'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
       pre_dispatch='2*n_jobs', refit=True, scoring=None, verbose=3)

In [44]:
grid.best_params_

{'C': 1, 'gamma': 1, 'kernel': 'rbf'}

In [45]:
grid.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=1, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [46]:
grid_predictions = grid.predict(X_test)

In [47]:
print confusion_matrix(y_test,grid_predictions)
print '\n'
print classification_report(y_test,grid_predictions)

[[64  4]
 [ 3 29]]


             precision    recall  f1-score   support

          0       0.96      0.94      0.95        68
          1       0.88      0.91      0.89        32

avg / total       0.93      0.93      0.93       100



In [48]:
classifier = SVC(kernel='rbf',C=1,gamma=1)
classifier.fit(X_train,y_train)
y_pred = classifier.predict(X_test)
print classification_report(y_test,y_pred)
print '\n'
print confusion_matrix(y_test,y_pred)

             precision    recall  f1-score   support

          0       0.96      0.94      0.95        68
          1       0.88      0.91      0.89        32

avg / total       0.93      0.93      0.93       100



[[64  4]
 [ 3 29]]
